---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: notes-app-cicd
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/juanpenarivera/notes-app-cicd
